### ISSUE TITLE
Comparison with Quartz.NET 2.3.2

### ISSUE THREAD

**Issue by lahma** [tswanepoel/crongadgetry#1]
Would it be possible for you to re-run the comparison against the latest released Quartz.NET 2.3.2 version?

I have fixed a small issue that was causing a lot of object allocations when running cron expression parsing in a tight loop. Probably will not be as fast as your implementation but some gap might have been removed.

**Comment by tswanepoel** [comment]
Hi lahma. Thanks for letting me know, and thank you for your interest in this project. Sure, it would be very interesting to see the effect of your fix. Will let you know soon.

**Comment by tswanepoel** [comment]
Hi lahma. I've update the README.md with the latest comparison with Quartz .NET 2.3.2. The changes you've made yield major performance improvements. My results suggest, on average, around 15x faster! Good work.

**Comment by lahma** [comment]
Thanks, great to see that it made some difference. Keep up the good work with your project too.

Cheers!
